### ISSUE TITLE
Dialog Window Height Issue

### ISSUE THREAD

**Issue by moiSentineL** [AbhiK002/Tasky#2] opened 2022-03-29 08:10 UTC
New task dialog window height issue. 

The 'save' and 'cancel buttons get pushed below.
This is a known issue of tkinter because it's not dynamic and the window thingy is different for all resolutions.

![image](https://user-images.githubusercontent.com/68242099/160564681-64e42966-bcb4-4101-a521-52dc86c2867d.png)
[Link to Image](https://i.imgur.com/0RMSvXr.png)

Monitor Resolution: 1920x1080; 115% Custom Scaling (Windows 10 Display Settings)

**Comment by AbhiK002** [comment] 2022-03-29 08:28
Thanks for reporting, on it!

**Comment by AbhiK002** [comment] 2022-03-29 09:10
![image](https://user-images.githubusercontent.com/68178267/160575418-7dc41ae0-ef2d-4f8d-afeb-57f04f3951c7.png)
Resolution: 1920x1080; 115% Custom Scaling
The issue is now fixed. Thanks again for reporting this!

**Closed** 2022-03-29 09:11 UTC
Labels: bug

**Comment by moiSentineL** [comment] 2022-03-29 09:44
that's awesome
